name: Build and Push Node.js

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - yolks/node/**
      - .github/workflows/nodejs.yml

jobs:
  build-and-push:
    name: Build and Push yolks:node_${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 24
          - 25

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Enable QEMU for multi-platform builds
      - uses: docker/setup-qemu-action@v3

      # 3️⃣ Setup Docker Buildx
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # 4️⃣ Login to GHCR using GitHub Token
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Build and push the Docker image
      - uses: docker/build-push-action@v5
        with:
          context: ./yolks/node
          file: ./yolks/node/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/enum314/node_${{ matrix.tag }}
